#!/bin/bash
# Apply Adwaita GTK & Icon Theme
#xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita" &
gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita' &
#xfconf-query -c xsettings -p /Net/IconThemeName -s "Adwaita" &
#xfconf-query -c xfwm4 -p /general/theme -s "Adwaita" &
#xfconf-query -c xfwm4 -p /general/theme -s "TOS-X4" &
#xfconf-query -c xfwm4 -p /general/theme -s "Zukitre" &
#xfconf-query -c xfwm4 -p /general/theme -s "Breeze-light" &
#xfconf-query -c xfwm4 -p /general/button_layout -s "O|HMC" &

# Apply Emacs Theme
emacsclient --eval '(with-current-buffer (window-buffer)(modus-themes-light))' &
#emacsclient --eval "(with-current-buffer (window-buffer)(tool-bar-mode 0))" &

# Set Wallpaper
#feh --bg-scale ~/.earth.jpg &
#xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP1/workspace0/last-image -s /home/diamond/Pictures/Wallpapers/.light.jpg &
#xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitoreDP1/workspace0/last-image -s /home/diamond/Pictures/Wallpapers/.light.jpg &

# Set Rofi Theme
#rm -f ~/.config/rofi/config.rasi

# Reload Panel
#xfce4-panel -q
#sleep 1; xfce4-panel &

#killall plank;

# Switch openbox theme
#fileName=y
#sed -i "s/$(grep "<theme>" ~/.config/openbox/rc.xml -A 5 | grep "<name>"| awk -F"[><]" '{print $3}')/$fileName/g" ~/.config/openbox/rc.xml
#openbox --reconfigure

