#!/bin/sh
# X11
xinput | grep 'ELAN224A' | grep 'pointer' | grep -Po 'id=\d+' | cut -d= -f2 | xargs xinput disable &
xrandr --output eDP-1 --set "scaling mode" "Full" &
xset b off &
xrdb -merge ~/.Xresources &

# Emacs
if pgrep 'emacs' > /dev/null
then
    echo "emacs running, everything is fine"
else
    echo "launching emacs"
    emacs --daemon &
fi

# Exports
export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
