#!/bin/bash
# Start Compositor
compton \
	--config /dev/null \
	--backend "glx" \
	--vsync "opengl-swc" \
	--detect-client-leader \
	--detect-transient \
	--detect-client-opacity \
	--paint-on-overlay \
	--glx-no-stencil \
	--glx-swap-method undefined \
	--unredir-if-possible \
	--unredir-if-possible-exclude "class_g = 'Light-locker'" \
	--inactive-opacity-override \
	--mark-wmwin-focused \
	--mark-ovredir-focused \
	--use-ewmh-active-win \
	--shadow-exclude "! name~=''" \
	--shadow-exclude "name = 'Notification'" \
	--shadow-exclude "name *= 'compton'" \
	--shadow-exclude "class_g ?= 'Notify-osd'" \
	--shadow-exclude "class_g ?= 'Cairo-dock'" \
	--shadow-exclude "class_g = 'Cairo-clock'" \
	--shadow-exclude "_GTK_FRAME_EXTENTS@:c" &
