#!/bin/bash
#xdotool windowsize `xdotool getactivewindow` 964 1150 #966 1185
#xdotool windowsize `xdotool getactivewindow` 980 1280
xdotool windowsize `xdotool getactivewindow` 939 1017
#xdotool windowsize `xdotool getactivewindow` 1091 1248
#1040 1280
