#!/bin/sh
echo "Host:" $(cat /etc/hostname)
echo $(lsb_release -d)
echo "Kernel:" $(uname -rs)
echo "Pkg count:" $(dpkg -l | grep -c ^i)
echo "RAM:" $(awk '/MemFree/ { printf "%.1f \n", $2/1024/1024 }' /proc/meminfo) "free of" $(awk '/MemTotal/ { printf "%.1f \n", $2/1024/1024 }' /proc/meminfo)
echo $(uptime -p)
echo 
echo $(fortune)
sleep 9999
