#!/bin/bash
if xinput list | grep "ROG KERIS  " > /dev/null
then
    sh -c ~/bin/rogkmaccel
else
    echo "ROG KERIS not plugged in" > /dev/null
fi

# Viper Mini
if xinput list | grep "Viper Mini  " > /dev/null
then
    sh -c && ~/bin/kmviperaccel
else
    echo "Viper Mini not plugged in" > /dev/null
fi
