#!/bin/bash

# Check if gedit is running
# -x flag only match processes whose name (or command line if -f is
# specified) exactly match the pattern. 

if pgrep -x "mpd" > /dev/null
then
    xfce4-terminal --geometry 55x15 -e ncmpcpp &
else
    mpd &
    xfce4-terminal --geometry 55x15 -e ncmpcpp &
fi

