#!/bin/bash
# Called by ~/.xinitrc

# Export Lang & Locale
export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

# Defaults & Keymaps
#userresources=$HOME/.Xresources
#usermodmap=$HOME/.Xmodmap
#sysresources=/etc/X11/xinit/.Xresources
#sysmodmap=/etc/X11/xinit/.Xmodmap

# Merge in defaults and keymaps
#[ -f $sysresources ] && xrdb -merge $sysresources
#[ -f $sysmodmap ] && xmodmap $sysmodmap
#[ -f "$userresources" ] && xrdb -merge "$userresources"
#[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# XDG/GDK
export XDG_SESSION_TYPE=X11
export GDK_BACKEND=x11

# Override style for QT applications
export QT_STYLE_OVERRIDE=gtk
export QT_SCALE_FACTOR=0.5

# Fix misbehaving Java applications
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D &

# X11 settings
xset b off &
xinput | grep 'ELAN224A' | grep 'pointer' | grep -Po 'id=\d+' | cut -d= -f2 | xargs xinput disable &
#xrdb -merge ~/.Xresources &
xrdb /home/diamond/.Xresources &

# Set root
#dwmblocks &
while true; do
	xsetroot -name "$(uptime | sed 's/.*,//') | $(/home/diamond/bin/battery) | $(date +%F) $(date +%I:%M) $(date +%p)"
	sleep 60
done &

# Set Pulseaudio default sink
pactl set-default-sink 0 &

# Init keyring
#export SSH_AUTH_SOCK
#eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)

# Export keyring globals
#export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK

# Start user defined programs
lxpolkit &
hsetroot -solid "#808080" &
#hsetroot -solid "#000000" &
dunst &
#light-locker &
xss-lock slock &
libinput-gestures &
nm-applet &
blueman-applet &
volumeicon &
dropbox start -i &
xfce4-power-manager &
matebook-applet &
emacs --daemon &

# Start Emacs
#if pgrep 'emacs' > /dev/null
#then
#	echo "emacs running, everything is fine"
#else
#	echo "launching emacs"
#	emacs --daemon &
#fi

# Start Compositor
compton \
	--config /dev/null \
	--backend "glx" \
	--vsync "opengl-swc" \
	--detect-client-leader \
	--detect-transient \
	--detect-client-opacity \
	--paint-on-overlay \
	--glx-no-stencil \
	--glx-swap-method undefined \
	--unredir-if-possible \
	--unredir-if-possible-exclude "class_g = 'Light-locker'" \
	--inactive-opacity-override \
	--mark-wmwin-focused \
	--mark-ovredir-focused \
	--use-ewmh-active-win \
	--shadow-exclude "! name~=''" \
	--shadow-exclude "name = 'Notification'" \
	--shadow-exclude "name *= 'compton'" \
	--shadow-exclude "class_g ?= 'Notify-osd'" \
	--shadow-exclude "class_g ?= 'Cairo-dock'" \
	--shadow-exclude "class_g = 'Cairo-clock'" \
	--shadow-exclude "_GTK_FRAME_EXTENTS@:c" &

#exec dbus-launch /usr/local/bin/dwm

#while true; do
#    # Log stderror to a file
#    #dwm 2> ~/.dwm.log
#    # No error logging
#    #dwm >/dev/null 2>&1
#    dbus-launch /usr/local/bin/dwm 2> /dev/null
#done

# relaunch DWM if the binary changes, otherwise bail
# csum=""
# new_csum=$(sha1sum $(which dwm))
# while true
# do
#     if [ "$csum" != "$new_csum" ]
#     then
#         csum=$new_csum
# 	#dbus-launch /usr/local/bin/dwm 2> /dev/null
# 	dwm || exit
#     else
#         exit 0
#     fi
#     new_csum=$(sha1sum $(which dwm))
#     sleep 0.5
# done

# Note: the "dwm || exit" allows you to exit dwm more intuitively by calling "$ killall dwm" instead of having to remember the script name and typing "$ killall startdwm". You can still restart dwm simply by hitting ALT+SHIFT+Q as long as you have that while-loop. 

#while true; do
##dwm 2> ~/.dwm.log || exit		# logging debug
#	dwm || exit
#done

dwm
