#!/bin/bash
if pgrep 'tint2' > /dev/null
then
    echo "tint2 running"
    killall tint2
else
    echo "tint2 not running"
fi
cp /home/diamond/.config/tint2/dockedboii /home/diamond/.config/tint2/tint2rc

#sleep 1;
tint2 &
#notify-send "Panel docked"
