#!/bin/sh
currUrl=$(cat /sys/class/power_supply/BAT0/current_now)
voltUrl=$(cat /sys/class/power_supply/BAT0/voltage_now)
power=$(expr "$currUrl" \* "$voltUrl")
conv_power=$(expr "$power" / 1000000000000)
echo $conv_power"W"
