#!/bin/bash

# get emacs window id
win=$(xdotool search --onlyvisible --class emacs | head -1)

if [ "x$win" = x ]; then
	if pgrep 'emacs' > /dev/null
	then
		echo "emacs running, everything is fine"
	else
		echo "launching emacs"
		tangle.sh
		emacs --daemon
	fi

	exec /usr/local/bin/emacsclient -c -n -a 'emacs' &
else
	if [ $win = $(xdotool getwindowfocus) ]; then
		sleep 0.1;
	else
		xdotool windowactivate $win
	fi
fi
