#!/usr/bin/env python3
import time

def time_convert(sec):
    sec = sec % 60
    print("time: {0}".format(sec))

start_time = time.time()

input("")
end_time = time.time()

time_lapsed = end_time - start_time
time_convert(time_lapsed)
