#!/usr/bin/env python3
import time

start_time = time.time()
input()
end_time = time.time()

time_lapsed = end_time - start_time
print(time_lapsed)

file = open("time.txt", "a")
file.write(str(time_lapsed) + "\n")
file.close()

print()
