#!/bin/bash

TOGGLE=/tmp/toggle_compositing

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    xfconf-query -c xfwm4 -p /general/use_compositing -s true
    #picom &
else
    rm $TOGGLE
    xfconf-query -c xfwm4 -p /general/use_compositing -s false
    #killall picom
fi
