#!/bin/bash

TOGGLE=/tmp/toggle_compositing

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    #xfconf-query -c xfwm4 -p /general/use_compositing -s true
    if pgrep 'picom' > /dev/null
    then
        echo "picom running"
        #killall picom
    else
        echo "picom not running"
    fi
    killall picom
    notify-send "Compositing enabled."
    picom &
    #feh --bg-scale ~/.earth.jpg &
else
    rm $TOGGLE
    #xfconf-query -c xfwm4 -p /general/use_compositing -s false
    killall picom;
    notify-send "Compositing disabled."
    #feh --bg-scale ~/.earth.jpg &
fi
