#!/bin/bash
if pgrep -x "picom" > /dev/null
then
	killall picom
	notify-send "compositor killed"
else
	picom -b --experimental-backends --config ~/.config/picom.conf
	notify-send "compositor started"
fi

# if [ "$(gsettings get org.mate.Marco.general compositing-manager)" = "true" ]
# then
#   gsettings set org.mate.Marco.general compositing-manager false
# else
#   gsettings set org.mate.Marco.general compositing-manager true
# fi

