#!/bin/bash

IFS='x' read screenWidth screenHeight < <(xdpyinfo | grep dimensions | grep -o '[0-9x]*' | head -n1)

width=$(xdotool getactivewindow getwindowgeometry --shell | head -4 | tail -1 | sed 's/[^0-9]*//')
height=$(xdotool getactivewindow getwindowgeometry --shell | head -5 | tail -1 | sed 's/[^0-9]*//')

newPosX=$((screenWidth / 2 - width / 2))
PosY=$((screenHeight / 2 - height / 2))
newPosY=$((PosY - 45)) #large panel

xdotool getactivewindow windowmove "$newPosX" "$newPosY"
